local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":h:h")
vim.opt.rtp:prepend(root)
local cells = require("ipynb.cells")
vim.api.nvim_buf_set_lines(0, 0, -1, false, {
  "# example", "", "```python", "print(1)", "```", "", "```python", "print(2)", "```",
})
vim.api.nvim_win_set_cursor(0, { 4, 0 })
assert(cells.current().first == 2)
cells.advance()
assert(vim.api.nvim_win_get_cursor(0)[1] == 8)
cells.advance()
assert(vim.api.nvim_get_current_line() == "")
local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
assert(lines[11] == "```python" and lines[13] == "```")
cells.add("markdown")
lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
assert(table.concat(lines, "\n"):find("<!-- #region -->", 1, true))
vim.api.nvim_win_set_cursor(0, { 1, 0 })
assert(cells.current() == nil)
print("pass: cell detection, advance, append code and markdown")
